name: mvp_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  material_design_icons_flutter: ^7.0.7296
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.8.12 
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  tflite: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model_unquant.tflite
    - assets/labels.txt