name: mvp_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_auth_web: ^5.8.12 
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  google_fonts: ^6.2.1
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: Noto Serif
      fonts:
        - asset: fonts/NotoSerif-Regular.ttf
        - asset: fonts/NotoSerif-Bold.ttf
          weight: 700
    - family: Noto Sans Mono
      fonts:
        - asset: fonts/NotoSansMono-Regular.ttf
        - asset: fonts/NotoSansMono-Bold.ttf
          weight: 700
