// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC27gBoSy6ui3xi8gK9QkEEL0pyDhGykm4',
    appId: '1:528210175222:web:c88354e2e78c8adc3638d7',
    messagingSenderId: '528210175222',
    projectId: 'mvp-project-8e55a',
    authDomain: 'mvp-project-8e55a.firebaseapp.com',
    storageBucket: 'mvp-project-8e55a.appspot.com',
    measurementId: 'G-7XQNG4Y0PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-pGQzTD5XrVJrBCn6_LAqTj-taqAjrJs',
    appId: '1:528210175222:android:a96e330f0bcfdce33638d7',
    messagingSenderId: '528210175222',
    projectId: 'mvp-project-8e55a',
    storageBucket: 'mvp-project-8e55a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnhER6Jun-VHsI-975eorqP5qcDH4omo',
    appId: '1:528210175222:ios:125f80bbcfb151a13638d7',
    messagingSenderId: '528210175222',
    projectId: 'mvp-project-8e55a',
    storageBucket: 'mvp-project-8e55a.appspot.com',
    iosBundleId: 'com.example.mvpProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnhER6Jun-VHsI-975eorqP5qcDH4omo',
    appId: '1:528210175222:ios:125f80bbcfb151a13638d7',
    messagingSenderId: '528210175222',
    projectId: 'mvp-project-8e55a',
    storageBucket: 'mvp-project-8e55a.appspot.com',
    iosBundleId: 'com.example.mvpProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC27gBoSy6ui3xi8gK9QkEEL0pyDhGykm4',
    appId: '1:528210175222:web:4d7ba8fae6d629a43638d7',
    messagingSenderId: '528210175222',
    projectId: 'mvp-project-8e55a',
    authDomain: 'mvp-project-8e55a.firebaseapp.com',
    storageBucket: 'mvp-project-8e55a.appspot.com',
    measurementId: 'G-9G2KJCWK8F',
  );
}
